Fix warnings for Rust 1.85.1 in packages/modules/Bluetooth
```
FAILED: out/soong/.intermediates/packages/modules/Bluetooth/offload/leaudio/audio/libbluetooth_offload_leaudio_audio/linux_glibc_x86_64_shared/libbluetooth_offload_leaudio_audio.so.clippy
ANDROID_RUST_VERSION=1.85.1 out/host/linux-x86/bin/rustc_wrapper prebuilts/rust/linux-x86/1.85.1/bin/clippy-driver --emit metadata -o out/soong/.intermediates/packages/modules/Bluetooth/offload/leaudio/audio/libbluetooth_offload_leaudio_audio/linux_glibc_x86_64_shared/libbluetooth_offload_leaudio_audio.so.clippy --emit dep-info=out/soong/.intermediates/packages/modules/Bluetooth/offload/leaudio/audio/libbluetooth_offload_leaudio_audio/linux_glibc_x86_64_shared/libbluetooth_offload_leaudio_audio.so.clippy.d.raw packages/modules/Bluetooth/offload/leaudio/audio/lib.rs --extern android_hardware_bluetooth_offload_leaudio=out/soong/.intermediates/packages/modules/Bluetooth/offload/leaudio/aidl/android.hardware.bluetooth.offload.leaudio-rust/linux_glibc_x86_64_rlib_rlib-std/libandroid_hardware_bluetooth_offload_leaudio.rlib --extern binder=out/soong/.intermediates/frameworks/native/libs/binder/rust/libbinder_rs/linux_glibc_x86_64_rlib_rlib-std/libbinder_rs.rlib --extern log=out/soong/.intermediates/external/rust/android-crates-io/crates/log/liblog_rust/linux_glibc_x86_64_rlib_rlib-std/liblog_rust.rlib --extern logger=out/soong/.intermediates/system/logging/rust/liblogger/linux_glibc_x86_64_rlib_rlib-std/liblogger.rlib --extern std=prebuilts/rust/linux-x86/1.85.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-7db8ef8b6d15f2e7.rlib -L out/soong/.intermediates/frameworks/native/libs/binder/rust/libbinder_rs/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/static_assertions/libstatic_assertions/linux_glibc_x86_64_rlib_rlib-std/ -L prebuilts/rust/linux-x86/1.85.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/async-trait/libasync_trait/linux_glibc_x86_64/ -L out/soong/.intermediates/frameworks/native/libs/binder/rust/libbinder_ndk_sys/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/downcast-rs/libdowncast_rs/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/libc/liblibc/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/log/liblog_rust/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/zerocopy/libzerocopy/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/frameworks/native/libs/binder/ndk/libbinder_ndk/linux_glibc_x86_64_shared/ -L prebuilts/rust/linux-x86/1.85.1/lib/rustlib/x86_64-unknown-linux-gnu/lib -L out/soong/.intermediates/external/rust/android-crates-io/crates/zerocopy-derive/libzerocopy_derive/linux_glibc_x86_64/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/env_filter/libenv_filter/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/env_logger/libenv_logger/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/regex/libregex/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/aho-corasick/libaho_corasick/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/memchr/libmemchr/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/regex-automata/libregex_automata/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/regex-syntax/libregex_syntax/linux_glibc_x86_64_rlib_rlib-std/ -L prebuilts/clang/host/linux-x86/clang-r547379/lib/clang/20/lib/linux/ -L out/soong/.intermediates/external/liblc3/liblc3/linux_glibc_x86_64_static/ -L out/soong/.intermediates/external/opus-experimental/libopus-experimental/linux_glibc_x86_64_static/ -Z unstable-options -Z stack-protector=strong -Z remap-cwd-prefix=. -C debuginfo=2 -C opt-level=3 -C overflow-checks=on -C force-unwind-tables=yes -C symbol-mangling-version=v0 --color=always -Z dylib-lto -Z link-native-libraries=no -Z force-unstable-if-unmarked --cfg soong -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/x86_64-linux/lib32 -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/x86_64-linux/lib64 -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/lib/gcc/x86_64-linux/4.8.3 -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot/usr/lib  -C lto=thin -C relocation-model=pic -A deprecated -A unknown_lints -D missing-docs -D warnings -D unsafe_op_in_unsafe_fn --edition=2021 -C metadata=libbluetooth_offload_leaudio_audio --cfg 'feature="lc3"' --cfg 'feature="opus"' --crate-type=cdylib --crate-name=bluetooth_offload_leaudio_audio --target=x86_64-unknown-linux-gnu --sysroot=/dev/null -C codegen-units=1 -Zallow-features="" -A clippy::disallowed_names -A clippy::empty_line_after_doc_comments -A clippy::type-complexity -A clippy::unnecessary_fallible_conversions -A clippy::unnecessary-wraps -A clippy::unusual-byte-groupings -A clippy::upper-case-acronyms -D clippy::undocumented_unsafe_blocks && grep ^out/soong/.intermediates/packages/modules/Bluetooth/offload/leaudio/audio/libbluetooth_offload_leaudio_audio/linux_glibc_x86_64_shared/libbluetooth_offload_leaudio_audio.so.clippy: out/soong/.intermediates/packages/modules/Bluetooth/offload/leaudio/audio/libbluetooth_offload_leaudio_audio/linux_glibc_x86_64_shared/libbluetooth_offload_leaudio_audio.so.clippy.d.raw > out/soong/.intermediates/packages/modules/Bluetooth/offload/leaudio/audio/libbluetooth_offload_leaudio_audio/linux_glibc_x86_64_shared/libbluetooth_offload_leaudio_audio.so.clippy.d
error: operator precedence can trip the unwary
   --> packages/modules/Bluetooth/offload/leaudio/audio/codec.rs:111:51
    |
111 |                 let v = it.fold(0i32, |v, (i, b)| v | (*b as i32) << (i * 8 + (32 - BITDEPTH)));
    |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider parenthesizing your expression: `v | ((*b as i32) << (i * 8 + (32 - BITDEPTH)))`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#precedence
    = note: `-D clippy::precedence` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::precedence)]`

error: aborting due to 1 previous error
```

Bug: 421269002
Test: m rust
Flag: EXEMPT refactor
Change-Id: I05976fa41155e8affbbc3bdd6d1694756e5ef310