Allow all BassClientService operations directly if on scan thread
Similar to ag/36873293. If a callback in `BassClientService` is already
on the scan thread, it now calls these methods directly to prevent a
crash:
  java.lang.IllegalStateException: Must NOT be on scan thread

This time we introduce a `runOnScanThread(Runnable)` helper to reduce
boilerplate code when verifying `mScanController.isOnScanThread()`.

Fix: 487582142
Bug: 397863857
Test: atest com.android.bluetooth.bass_client
Flag: com.android.bluetooth.flags.scan_controller_thread
Change-Id: Iaead0c17540466974b92033a44a0c6a3f79cd0a7