Remove unused field
Fixes new code warning found by clang-r563880.

In file included from packages/modules/Bluetooth/system/btif/avrcp/avrcp_service.cc:17:
packages/modules/Bluetooth/system/btif/avrcp/avrcp_service.h:110:12: error: private field 'sdp_record_handle' is not used [-Werror,-Wunused-private-field]
  110 |   uint32_t sdp_record_handle = -1;
      |            ^

Test: presubmit
Test: m dist
Bug: 401330760
Flag: EXEMPT, dead code removal
Change-Id: Ie8a41d95a261b8b439427ad829f6374a866909a7