Remove obsolete SDK_INT check
With the upgrade of Android Lint in change Ibcf8a6fbf7536667d60f89b5824cb59250e33860, lint is catching that this check is obsolete (the min_sdk_version on BluetoothLib is already 36).

Remove the check so that the lint error will go away with the new lint version:
```
packages/modules/Bluetooth/android/app/src/com/android/bluetooth/le_audio/LeAudioService.java:422: Error: Unnecessary; SDK_INT is always >= 36 [ObsoleteSdkInt]
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
```

Bug: 441794572
Test: atest CtsBluetoothTestCases
Flag: EXEMPT PURE_REFACTOR
Change-Id: I8c2bbd5f7ead1c4096ab8eb916166b22ac41ed54