Remove unused 'using' declaration
Since http://ag/37738629, the only usage of ToString disappeared and it
is now failing nightly builds

```
error: using decl 'ToString' is unused [misc-unused-using-decls,-warnings-as-errors]
   32 | using bluetooth::common::ToString;
      |                          ^
```


We should consider adding some flag in build time in normal build to
prevent postsubmit breakage

Bug: 474507455
Fix: 474507455
Test: m .
Flag: EXEMPT BUGFIX
Change-Id: I6a6a6964c624940e666399d8fec035190cf3ea91