Remove manual `ktfmt` PREUPLOAD hook to reuse alint ktfmt at `v0.62`
This will allow us to use a version synced with alint all the time
instead of depending a different version under /external/ktfmt.

Broke a formatting on purpose to yield:

```
[COMMIT 1/2 7195a3447b50] Remove manual `ktfmt` PREUPLOAD hook to reuse alint ktfmt at `v0.62`
[FAILED] alint hook
    Running alint
    ERROR: [KotlinFormatter/KotlinFormatter] android/app/src/com/android/bluetooth/le_scan/ScanUtil.kt: FAIL: Use `/google/bin/releases/kotlin-google-eng/ktfmt/ktfmt --kotlinlang-style android/app/src/com/android/bluetooth/le_scan/ScanUtil.kt` or one of the other ways(go/ktfmt#how-to-use-ktfmt). To disable this check, add `NO_KTFMT=<reason>` to your CL commit message.
    INFO: Fixes available, please run `/google/bin/releases/alint/alint fix` to apply.
    Analyzer returned actionable finding
    Alint binary returned findings. Please fix before uploading..
```

Fix: 494070244
Test: atest BluetoothJavaUnitTests
Flag: EXEMPT PURE_REFACTOR
Change-Id: Ie95ad7095a1db7bba68850814f18287247af8ca5