Fix nonnull warning for std::string
std::string should only be assigned non-null values (string, c-string,
char) so it cannot be assigned null values (0 or nullptr) which caused the
warning. We can fix this by returning an empty string.

packages/modules/Bluetooth/system/test/stub/osi.cc:132:10: error: null
passed to a callee that requires a non-null argument [-Werror,-Wnonnull]
  132 |   return 0;
      |          ^
1 error generated.

packages/modules/Bluetooth/system/test/mock/mock_stack_a2dp_codec_config.cc:266:10:
error: null passed to a callee that requires a non-null argument
[-Werror,-Wnonnull]
  266 |   return 0;
      |          ^
packages/modules/Bluetooth/system/test/mock/mock_stack_a2dp_codec_config.cc:271:10:
error: null passed to a callee that requires a non-null argument
[-Werror,-Wnonnull]
  271 |   return 0;
      |          ^
packages/modules/Bluetooth/system/test/mock/mock_stack_a2dp_codec_config.cc:276:10:
error: null passed to a callee that requires a non-null argument
[-Werror,-Wnonnull]
  276 |   return 0;
      |          ^
packages/modules/Bluetooth/system/test/mock/mock_stack_a2dp_codec_config.cc:280:10:
error: null passed to a callee that requires a non-null argument
[-Werror,-Wnonnull]
  280 |   return 0;
      |          ^
packages/modules/Bluetooth/system/test/mock/mock_stack_a2dp_codec_config.cc:285:10:
error: null passed to a callee that requires a non-null argument
[-Werror,-Wnonnull]
  285 |   return 0;
      |          ^
5 errors generated.

Flag: EXEMPT warning fix
Bug: 430598176
Test: m && presubmits
Change-Id: Ie7ea8660c15115c192c2057b17b70909199ce836